name: app
description: 꽃갈피 프로젝트
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6 # 2023.01.20. - http 통신
  flutter_secure_storage: ^7.0.1 # 2023.01.20. - 내부 저장소
  json_serializable: ^6.5.4 # 2023.01.20.
  json_annotation: ^4.8.0 # 2023.01.20.
  flutter_riverpod: ^2.1.3 # 2023.01.20. - 프로바이더 상태관리
  retrofit: '>=3.0.0 <4.0.0' # 2023.01.20. - http 통신 api 상태관리
  logger: any # 2023.01.20.
  skeletons: ^0.0.3 # 2023.01.20. - 로딩 스켈레톤
  go_router: ^6.0.1 # 2023.01.20. - 라우터
  badges: ^2.0.3 # 2023.01.20. - 푸시알림 뱃지
  uuid: ^3.0.6 # 2023.01.20. - 유저 정보 uuid
  debounce_throttle: ^2.0.0 # 2023.01.20. - 로딩 디바운스 + 쓰로틀
  card_swiper: ^2.0.4 # 2023.01.20. - 카드 스와이퍼
  flutter_dotenv: ^5.0.2 # 2023.01.24. - 컨피그 파일
  kakao_flutter_sdk_user: ^1.3.1 # 2023.01.24. 카카오 로그인
  flutter_naver_login: ^1.7.0 # 2023.01.25 네이버 로그인
  flutter_web_auth: ^0.5.0 # 2023.01.26. 네이버 로그인을 위해

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3 # 2023.01.20.
  retrofit_generator: '>=4.0.0 <5.0.0' # 2023.01.20.

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/config/.env
  
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 900
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 700
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 200
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 100