# Generated by Django 4.0.2 on 2022-03-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gongmore',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=100)),
                ('part', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('listdate', models.CharField(max_length=100)),
            ],
        ),
    ]
